# Generated by Django 5.1.15 on 2026-08-12 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentalhealth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crisisescalation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='mentalhealth.chatsession'),
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentalhealth.chatsession'),
        ),
        migrations.AddField(
            model_name='crisisescalation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='mentalhealth.message'),
        ),
    ]
