# Generated by Django 5.1.15 on 2026-08-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='bi-chat-heart', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_auth_for_full_access', models.BooleanField(default=True)),
                ('api_base_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
